version: '2'
services:
  web:
    build: .
    expose:
      - "2222"
    ports:
      - "2222:2222"
    volumes:
      - .:/code
      - logvolume01:/var/log
    environment:
      - NODEMON=1

networks:
   default:
      external:
         name: nginxproxy_default

volumes:
  logvolume01: {}
