services:
  web:
    build: .
    expose:
      - "2222"
    ports:
      - "2222:2222"
    volumes:
      - .:/code
      - logvolume01:/var/log
    environment:
      NODEMON:
      SLEEPTIME: 0
      LOCALHOST: 1

networks:
   default:
      name: nginxproxy_default
      external: true

volumes:
  logvolume01: {}
